// ─── Core domain types for WorkPilot ────────────────────────────────────────
// Shared by agent-core (P1), frontend (P2), and server executor (P3).
// All external writes go through ActionPlan → Server Executor → Jira.
// The agent NEVER writes directly.
//
// Runtime validation: use parseActionPlan() / parseApprovalRequest() to
// validate untrusted input (API bodies, agent output) before use.
// These validators are intentionally dependency-free (no zod) so this
// package stays importable from both server and edge runtimes.

// ─── Jira primitives ─────────────────────────────────────────────────────────

export type Comment = {
  id: string
  author: string
  body: string
  created: string
}

export type RelatedIssue = {
  issueKey: string
  summary: string
  status: string
  linkType: string // "blocks" | "is blocked by" | "relates to" | ...
}

export type Subtask = {
  issueKey: string
  summary: string
  status: string
}

// ─── WorkContext ──────────────────────────────────────────────────────────────
// Snapshot of a Jira issue at the moment the agent reads it.
//
// Fields that trigger SNAPSHOT_CHANGED if they change before approval:
//   status, priority, assignee, existingSubtasks (keys), relatedIssues (keys)
//
// Fields intentionally excluded from the hash (do not trigger invalidation):
//   comments (append-only, new comments don't block execution)
//   summary   (cosmetic, doesn't affect action safety)
//   fetchedAt (always different)

export type WorkContext = {
  issueKey: string
  summary: string
  status: string
  priority: string
  assignee?: string
  comments: Comment[]
  relatedIssues: RelatedIssue[]
  existingSubtasks: Subtask[]
  snapshotVersion: string // opaque version token from Jira (e.g. etag or updated timestamp)
  snapshotHash: string    // deterministic hash of fields relevant to execution
  fetchedAt: string       // ISO timestamp
}

// ─── Evidence ────────────────────────────────────────────────────────────────
// Every agent conclusion must trace back to a Jira artifact.

export type Evidence = {
  sourceType: "issue" | "comment" | "relation" | "subtask"
  issueKey: string
  commentId?: string
  excerpt: string
  url?: string
}

// ─── Action ──────────────────────────────────────────────────────────────────
// A single proposed write. The executor processes each action independently.
//
// Error classification:
//   transient  → retryable: true  (network timeout, 429, 502/503/504)
//   permanent  → retryable: false (400 bad request, 404 not found, 403 forbidden)

export type ActionType =
  | "assign_issue"
  | "set_priority"
  | "create_subtask"
  | "add_comment"

export type ActionStatus =
  | "pending"
  | "approved"
  | "executing"
  | "succeeded"
  | "failed"
  | "skipped"    // idempotency: already executed
  | "reconciling" // uncertain outcome, read-back in progress

export type Action = {
  actionId: string
  type: ActionType
  payload: Record<string, unknown> // type-safe at call site via ActionPayloadMap
  before?: unknown
  after?: unknown
  evidenceRefs: string[] // Evidence excerpt references
  status: ActionStatus
  dryRun?: boolean // if true, log intent but do not write to Jira
  errorReason?: string // human-readable reason for failed/skipped status
}

// Typed payloads per action type — used by executor for safe access
export type ActionPayloadMap = {
  assign_issue:   { issueKey: string; user: string }
  set_priority:   { issueKey: string; priority: string }
  create_subtask: { parentKey: string; summary: string; description?: string; assignee?: string }
  add_comment:    { issueKey: string; body: string }
}

// ─── ActionPlan ───────────────────────────────────────────────────────────────
// Generated by the agent. Persisted server-side. Approved by the user.
// version increments on every regeneration — executor rejects stale versions.

export type ActionPlan = {
  planId: string
  version: number
  issueKey: string
  snapshotVersion: string
  snapshotHash: string   // must match WorkContext.snapshotHash at approval time

  findings: string[]       // FACTS: what Jira demonstrates
  hypotheses: string[]     // HYPOTHESES: agent interpretations
  missingInfo: string[]    // MISSING: data needed to act safely

  actions: Action[]

  slackDraft: {
    channel: string
    text: string
  }

  expiresAt: string  // ISO — executor rejects after this timestamp
  createdAt: string
  status: "pending" | "approved" | "rejected" | "executed" | "expired" | "invalidated"
}

// ─── Execution ────────────────────────────────────────────────────────────────
// Persistent record of every action execution attempt.
// One Execution row per action per approval attempt.
//
// Error classification stored in `retryable`:
//   true  → transient error, safe to retry (timeout, rate-limit, 5xx)
//   false → permanent error, do not retry (bad payload, 403, 404)

export type ExecutionStatus =
  | "started"
  | "succeeded"
  | "failed"
  | "uncertain"   // API responded but read-back inconclusive
  | "reconciled"  // uncertain → resolved via reconciliation

export type Execution = {
  executionId: string
  planId: string
  planVersion: number
  issueKey: string
  actionId: string
  startedAt: string
  finishedAt?: string
  status: ExecutionStatus
  provider: "jira" | "slack"
  providerId?: string  // real Jira issue key, comment ID, etc. from read-back
  error?: string
  errorCode?: string   // machine-readable: TIMEOUT | RATE_LIMITED | FORBIDDEN | NOT_FOUND | BAD_REQUEST | UNKNOWN
  retryable: boolean
  dryRun: boolean
  latencyMs?: number   // finishedAt - startedAt in ms, for metrics
}

// Machine-readable Jira error codes used in Execution.errorCode / ActionResult.errorCode
export type JiraErrorCode =
  | "TIMEOUT"
  | "RATE_LIMITED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "BAD_REQUEST"
  | "UNKNOWN"

export function statusToJiraErrorCode(status: number): JiraErrorCode {
  if (!status || status === 0) return "TIMEOUT"
  if (status === 429) return "RATE_LIMITED"
  if (status === 403) return "FORBIDDEN"
  if (status === 404) return "NOT_FOUND"
  if (status === 400) return "BAD_REQUEST"
  return "UNKNOWN"
}

// ─── Approval request ────────────────────────────────────────────────────────
// Shape of POST /api/workpilot/approve body

export type ApprovalRequest = {
  planId: string
  version: number
  dryRun?: boolean
}

// ─── Approval result ─────────────────────────────────────────────────────────

export type ActionResult = {
  actionId: string
  status: ActionStatus
  providerId?: string
  error?: string
  errorCode?: string   // mirrors Execution.errorCode — returned to frontend
  retryable?: boolean  // frontend uses this to decide whether to show "Retry"
}

export type ApprovalResult = {
  planId: string
  issueKey: string
  actions: ActionResult[]
  slackStatus: "sent" | "pending" | "failed" | "skipped"
  slackProviderId?: string
}

// ─── Runtime validators ───────────────────────────────────────────────────────
// Validate untrusted input without a schema library.
// Throw with a descriptive message on invalid shape.

export function parseApprovalRequest(raw: unknown): ApprovalRequest {
  if (!raw || typeof raw !== "object") throw new Error("ApprovalRequest must be an object")
  const r = raw as Record<string, unknown>
  if (typeof r["planId"] !== "string" || !r["planId"]) {
    throw new Error("ApprovalRequest.planId must be a non-empty string")
  }
  if (typeof r["version"] !== "number" || !Number.isInteger(r["version"]) || r["version"] < 1) {
    throw new Error("ApprovalRequest.version must be a positive integer")
  }
  return {
    planId: r["planId"] as string,
    version: r["version"] as number,
    dryRun: r["dryRun"] === true,
  }
}

export function parseActionPlan(raw: unknown): ActionPlan {
  if (!raw || typeof raw !== "object") throw new Error("ActionPlan must be an object")
  const r = raw as Record<string, unknown>
  const required: Array<[string, string]> = [
    ["planId",          "string"],
    ["issueKey",        "string"],
    ["snapshotVersion", "string"],
    ["snapshotHash",    "string"],
    ["expiresAt",       "string"],
    ["createdAt",       "string"],
  ]
  for (const [field, type] of required) {
    if (typeof r[field] !== type || !r[field]) {
      throw new Error(`ActionPlan.${field} must be a non-empty ${type}`)
    }
  }
  if (typeof r["version"] !== "number" || !Number.isInteger(r["version"]) || r["version"] < 1) {
    throw new Error("ActionPlan.version must be a positive integer")
  }
  if (!Array.isArray(r["actions"])) throw new Error("ActionPlan.actions must be an array")
  return raw as ActionPlan
}
